server:
  port: ${PORT}
  server: ${SERVER_URL}

spring:
  application:
    name: briseyda-arbizu
  data:
    mongodb:
      # Si MONGO_URI no existe, usa la URL de Atlas por defecto
      uri: ${DATABASE_URL}
      database: ${DATABASE_USERNAME}

api:
  rapidapi:
    key: ${RAPIDAPI_APIKEY}
  background-remover:
    url: ${BACK_REMOVER_URL}
    host: ${BACK_REMOVER_HOST}
  photo-to-anime:
    url: ${PHOTO_ANIME_URL}
    host: ${PHOTO_ANIME_HOST}