# kubectl apply -f briseyda-arbizu-01-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: briseyda-arbizu-01-secret
  namespace: briseyda-arbizu-01-namespace
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly91c3VhcmlvOnBhc3N3b3JkQGNsdXN0ZXIubW9uZ29kYi5uZXQvdHVfYmQ=  # en Base64
  DATABASE_USERNAME: YnJpc2V5ZGE=   # en Base64
  DATABASE_PASSWORD: Ym9uaXRhYnJpczIw   # en Base64
  RAPIDAPI_URL: aHR0cHM6Ly9haS1iYWNrZ3JvdW5kLXJlbW92ZXIucC5yYXBpZGFwaS5jb20vaW1hZ2UvbWF0dGUvdjE=   # en Base64
  RAPIDAPI_HOST: YWdlLWRldGVjdG9yLnAucmFwaWRhcGkuY29t   # en Base64
  RAPIDAPI_APIKEY: MzA1NGRjYTI5NG1zaDMxMWZjYzE2ODkzY2U3NHAxN2VmMjRqc25jYmQ4ZWFkNmVkNzY=   # en Base64

# https://base64.guru/converter 
# echo -n "demo123" | base64 
# echo "ZGVtbzEyMw==" | base64 --decode