# kubectl apply -f briseyda-arbizu-01-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: briseyda-arbizu-01-secret
  namespace: briseyda-arbizu-01-namespace
type: Opaque
data:
  PORT: ODA4NQ==
  SERVER_URL: aHR0cDovL2xvY2FsaG9zdDo4MDg1
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9icmlzZXlkYTpib25pdGFicmlzMjBAY2x1c3RlcjAubHdza3F6ci5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==  # en Base64
  DATABASE_USERNAME: MDFfYnJpc2V5ZGFfQXJiaXp1   # en Base64
  RAPIDAPI_APIKEY: N2Q2OTBiYTdjN21zaGE3YzQ3NmQzNjFmY2EwN3AxMzBlNDJqc240YWEyZTA2ZmQ3MGY=   # en Base64
  BACK_REMOVER_URL: aHR0cHM6Ly9haS1iYWNrZ3JvdW5kLXJlbW92ZXIucC5yYXBpZGFwaS5jb20vaW1hZ2UvbWF0dGUvdjE=   # en Base64
  BACK_REMOVER_HOST: YWktYmFja2dyb3VuZC1yZW1vdmVyLnAucmFwaWRhcGkuY29t   # en Base64
  PHOTO_ANIME_URL: aHR0cHM6Ly9waG90b3RvYW5pbWUxLnAucmFwaWRhcGkuY29tL2NhcnRvb25pemU=
  PHOTO_ANIME_HOST: cGhvdG90b2FuaW1lMS5wLnJhcGlkYXBpLmNvbQ==
# https://base64.guru/converter 
# echo -n "demo123" | base64 
# echo "ZGVtbzEyMw==" | base64 --decode